# Generated by Django 6.0.2 on 2026-03-04 08:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ExpansionPolicyConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("key", models.SlugField(max_length=80, unique=True)),
                ("title", models.CharField(max_length=120)),
                ("is_active", models.BooleanField(default=True)),
                ("auto_mode_enabled", models.BooleanField(default=True)),
                (
                    "min_confidence",
                    models.FloatField(
                        default=0.7,
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(1.0),
                        ],
                    ),
                ),
                ("min_constraint_signals", models.PositiveSmallIntegerField(default=1)),
                ("notes", models.TextField(blank=True, default="")),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ("key",),
            },
        ),
        migrations.CreateModel(
            name="FeedbackReasonTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "scope",
                    models.CharField(choices=[("turn", "Turn"), ("item", "Item")], max_length=20),
                ),
                (
                    "polarity",
                    models.CharField(
                        choices=[("up", "Thumbs up"), ("down", "Thumbs down")], max_length=10
                    ),
                ),
                ("label", models.SlugField(max_length=80)),
                ("title", models.CharField(max_length=120)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ("scope", "polarity", "label"),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("scope", "polarity", "label"),
                        name="uniq_feedback_reason_scope_polarity_label",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="SystemPromptTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("key", models.SlugField(max_length=80)),
                ("version", models.CharField(max_length=40)),
                ("title", models.CharField(max_length=120)),
                ("template_text", models.TextField()),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ("key", "version"),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("key", "version"), name="uniq_prompt_key_version"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="PromptVariantSet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.SlugField(max_length=80, unique=True)),
                ("title", models.CharField(max_length=120)),
                ("description", models.TextField(blank=True, default="")),
                ("is_active", models.BooleanField(default=True)),
                (
                    "max_variants",
                    models.PositiveSmallIntegerField(
                        default=5,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "templates",
                    models.ManyToManyField(
                        blank=True, related_name="variant_sets", to="web.systemprompttemplate"
                    ),
                ),
            ],
            options={
                "ordering": ("name",),
            },
        ),
    ]
