# Generated by Django 6.0.2 on 2026-03-04 09:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="expansionpolicyconfig",
            options={
                "ordering": ("key",),
                "verbose_name": "Expansion policy",
                "verbose_name_plural": "Expansion policies (Query expansion)",
            },
        ),
        migrations.AlterModelOptions(
            name="feedbackreasontag",
            options={
                "ordering": ("scope", "polarity", "label"),
                "verbose_name": "Feedback reason tag",
                "verbose_name_plural": "Feedback reason tags (Ratings UI)",
            },
        ),
        migrations.AlterModelOptions(
            name="promptvariantset",
            options={
                "ordering": ("name",),
                "verbose_name": "Prompt variant set",
                "verbose_name_plural": "Prompt variant sets (Prompt Lab)",
            },
        ),
        migrations.AlterModelOptions(
            name="systemprompttemplate",
            options={
                "ordering": ("key", "version"),
                "verbose_name": "Prompt template",
                "verbose_name_plural": "Prompt templates (Search + Follow-up)",
            },
        ),
    ]
