/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/attachments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Upload Attachment
         * @description Upload one image and return a typed attachment reference.
         */
        post: operations["upload_attachment_attachments_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/attachments/{attachment_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Attachment
         * @description Serve one previously uploaded attachment by id.
         */
        get: operations["get_attachment_attachments__attachment_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/generated-images/floor-plan": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Generate Floor Plan Image
         * @description Generate and store a simple floor plan preview artifact.
         */
        post: operations["generate_floor_plan_image_generated_images_floor_plan_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/threads": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Threads */
        get: operations["list_threads_api_threads_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/threads/{thread_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Thread */
        get: operations["get_thread_api_threads__thread_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/threads/{thread_id}/title": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Thread Title */
        patch: operations["update_thread_title_api_threads__thread_id__title_patch"];
        trace?: never;
    };
    "/api/threads/{thread_id}/assets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Thread Assets */
        get: operations["list_thread_assets_api_threads__thread_id__assets_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/threads/{thread_id}/floor-plan-revisions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Thread Floor Plan Revisions */
        get: operations["list_thread_floor_plan_revisions_api_threads__thread_id__floor_plan_revisions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/threads/{thread_id}/analyses": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Thread Analyses */
        get: operations["list_thread_analyses_api_threads__thread_id__analyses_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/threads/{thread_id}/images/{asset_id}/detections": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Thread Detections For Image */
        get: operations["list_thread_detections_for_image_api_threads__thread_id__images__asset_id__detections_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AnalysisListItem
         * @description One persisted image-analysis run for a thread.
         */
        AnalysisListItem: {
            /** Analysis Id */
            analysis_id: string;
            /** Run Id */
            run_id: string | null;
            /** Tool Name */
            tool_name: string;
            /** Input Asset Id */
            input_asset_id: string;
            /** Created At */
            created_at: string | null;
        };
        /**
         * AssetListItem
         * @description One stored asset entry for thread inspection UIs.
         */
        AssetListItem: {
            /** Asset Id */
            asset_id: string;
            /** Run Id */
            run_id: string | null;
            /** Created By Tool */
            created_by_tool: string | null;
            /** Kind */
            kind: string;
            /** Mime Type */
            mime_type: string;
            /** File Name */
            file_name: string | null;
            /** Storage Path */
            storage_path: string;
            /** Size Bytes */
            size_bytes: number;
            /** Created At */
            created_at: string | null;
        };
        /**
         * DetectionListItem
         * @description Normalized detection row associated with one input image.
         */
        DetectionListItem: {
            /** Analysis Detection Id */
            analysis_detection_id: string;
            /** Analysis Id */
            analysis_id: string;
            /** Ordinal */
            ordinal: number;
            /** Label */
            label: string;
            /** Bbox X1 Px */
            bbox_x1_px: number;
            /** Bbox Y1 Px */
            bbox_y1_px: number;
            /** Bbox X2 Px */
            bbox_x2_px: number;
            /** Bbox Y2 Px */
            bbox_y2_px: number;
            /** Bbox X1 Norm */
            bbox_x1_norm: number;
            /** Bbox Y1 Norm */
            bbox_y1_norm: number;
            /** Bbox X2 Norm */
            bbox_x2_norm: number;
            /** Bbox Y2 Norm */
            bbox_y2_norm: number;
        };
        /**
         * FloorPlanRevisionListItem
         * @description One persisted floor-plan revision entry for a thread.
         */
        FloorPlanRevisionListItem: {
            /** Floor Plan Revision Id */
            floor_plan_revision_id: string;
            /** Revision */
            revision: number;
            /** Scene Level */
            scene_level: string;
            /** Svg Asset Id */
            svg_asset_id: string | null;
            /** Png Asset Id */
            png_asset_id: string | null;
            /** Confirmed At */
            confirmed_at: string | null;
            /** Confirmed By Run Id */
            confirmed_by_run_id: string | null;
            /** Confirmation Note */
            confirmation_note: string | null;
            /** Summary */
            summary: {
                [key: string]: unknown;
            };
            /** Created At */
            created_at: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * ThreadDetailItem
         * @description Thread detail including aggregate child counts.
         */
        ThreadDetailItem: {
            /** Thread Id */
            thread_id: string;
            /** Title */
            title: string | null;
            /** Status */
            status: string;
            /** Last Activity At */
            last_activity_at: string | null;
            /** Run Count */
            run_count: number;
            /** Asset Count */
            asset_count: number;
            /** Floor Plan Revision Count */
            floor_plan_revision_count: number;
            /** Analysis Count */
            analysis_count: number;
            /** Search Count */
            search_count: number;
        };
        /**
         * ThreadListItem
         * @description Lightweight thread summary for thread list UIs.
         */
        ThreadListItem: {
            /** Thread Id */
            thread_id: string;
            /** Title */
            title: string | null;
            /** Status */
            status: string;
            /** Last Activity At */
            last_activity_at: string | null;
        };
        /**
         * ThreadTitleUpdateRequest
         * @description Request payload to set a user-visible thread title.
         */
        ThreadTitleUpdateRequest: {
            /** Title */
            title: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    upload_attachment_attachments_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    get_attachment_attachments__attachment_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                attachment_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    generate_floor_plan_image_generated_images_floor_plan_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    list_threads_api_threads_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ThreadListItem"][];
                };
            };
        };
    };
    get_thread_api_threads__thread_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                thread_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ThreadDetailItem"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_thread_title_api_threads__thread_id__title_patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                thread_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ThreadTitleUpdateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ThreadDetailItem"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_thread_assets_api_threads__thread_id__assets_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                thread_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssetListItem"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_thread_floor_plan_revisions_api_threads__thread_id__floor_plan_revisions_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                thread_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FloorPlanRevisionListItem"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_thread_analyses_api_threads__thread_id__analyses_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                thread_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalysisListItem"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_thread_detections_for_image_api_threads__thread_id__images__asset_id__detections_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                thread_id: string;
                asset_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DetectionListItem"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
